MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
    FREEZE_AT: 0
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 10 #2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 10 #1000  # Per FPN level
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    POST_NMS_TOPK_TRAIN: 10 #1000
    POST_NMS_TOPK_TEST: 10 #1000
  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    BATCH_SIZE_PER_IMAGE: 128
    NUM_CLASSES: 1
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
    FED_LOSS_NUM_CLASSES: 1
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
  SEM_SEG_HEAD:
    NUM_CLASSES: 1
DATASETS:
  CLASS_NAMES: [ "Insect" ]
  TRAIN: ("wildbees_train",)
  TEST: ("wildbees_val",)
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 10 #1000
  PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 10 #2000
SOLVER:
  IMS_PER_BATCH: 64 #16
  BASE_LR: 0.01 #0.02
  STEPS: (600, 800) #(60000, 80000)
  MAX_ITER: 100 #1000 #90000
  WEIGHT_DECAY: 0.01 #0.0001
  CHECKPOINT_PERIOD: 200
INPUT:
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  COLOR_JITTER:
    BRIGHTNESS: True
    LIGHTING: True
    SATURATION: True
  GRID_MASK:
    ENABLED: False
    MODE: 1
    PROB: 0.3
    USE_HEIGHT: True
    USE_WIDTH: True
  RANDOM_FLIP: "horizontal"
  SHIFT:
    SHIFT_PIXELS: 32
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  FORMAT: "RGB"
  MASK_FORMAT: "bitmask"
TEST:
  EVAL_PERIOD: 10 #100
  DETECTIONS_PER_IMAGE: 10
VERSION: 2