_BASE_: "Base-SparseInst.yaml"
MODEL:
  BACKBONE:
    #FREEZE_AT: 2
    NAME: "build_resnet_vd_backbone"
INPUT:
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  COLOR_JITTER:
    BRIGHTNESS: True
    LIGHTING: True
    SATURATION: True
  GRID_MASK:
    ENABLED: False
    MODE: 1
    PROB: 0.3
    USE_HEIGHT: True
    USE_WIDTH: True
  RANDOM_FLIP: "horizontal"
  SHIFT:
    SHIFT_PIXELS: 32
  MASK_FORMAT: "bitmask" # for RLE format (must be same as in Base-SparseInst.yaml)
OUTPUT_DIR: "output/wildbees_sparse_inst_r50vd_giam_aug"
