_BASE_: "Base-SparseInst.yaml"
MODEL:
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_vd_backbone"
INPUT:
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  MASK_FORMAT: "bitmask" # for RLE format (must be same as in Base-SparseInst.yaml)
OUTPUT_DIR: "output/wildbees_sparse_inst_r50vd_giam_aug"
