_BASE_: "Base-YOLOv7.yaml"
MODEL:
  META_ARCHITECTURE: "YOLOMask"
  WEIGHTS: ""
  MASK_ON: True
  BACKBONE:
    NAME: "build_swin_transformer_backbone"
  SWIN:
    TYPE: "tiny"
    WEIGHTS: "weights/swin_tiny_patch4_window7_224.pth" # downloaded from https://github.com/microsoft/Swin-Transformer
    OUT_FEATURES: [1, 2, 3] # we might also want try res2, res3, res4, res5

  RESNETS:
    DEPTH: 50
    
  YOLO:
    ANCHORS:
      # Default from COCO
      [
        [[116, 90], [156, 198], [373, 326]],
        [[30, 61], [62, 45], [42, 119]],
        [[10, 13], [16, 30], [33, 23]],
      ]
    ANCHOR_MASK: [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
    CLASSES: 1
    IN_FEATURES: [1, 2, 3]
    CONF_THRESHOLD: 0.01
    NMS_THRESHOLD: 0.5
    IGNORE_THRESHOLD: 0.7
    VARIANT: "yolov7"
    LOSS_TYPE: "v7"
    LOSS:
      LAMBDA_IOU: 1.1
    NECK:
      TYPE: "fpn"
      WITH_SPP: true

INPUT:
  MASK_FORMAT: "bitmask"
  MIN_SIZE_TRAIN: (416, 512, 608, 768)
  MAX_SIZE_TRAIN: 1056
  MIN_SIZE_TEST: 200 #672
  MAX_SIZE_TEST: 800
  # open all augmentations
  JITTER_CROP:
    ENABLED: False
  RESIZE:
    ENABLED: False
    # SHAPE: (540, 960)
  DISTORTION:
    ENABLED: False
  MOSAIC_AND_MIXUP:
    ENABLED: True
    DEBUG_VIS: False
    ENABLE_MIXUP: False

SOLVER:
  #AMP:
  #  ENABLED: true
  BASE_LR: 0.01 #0.003
  STEPS: (300, 600) #(60000, 80000)
  WARMUP_FACTOR: 0.00033333
  WARMUP_ITERS: 100 #1500
  MAX_ITER: 1000 #190000
  LR_SCHEDULER_NAME: "WarmupMultiStepLR" #"WarmupCosineLR"

TEST:
  EVAL_PERIOD: 100
OUTPUT_DIR: "output/wildbees_yolomask/swin_t_backbone"
  
DATALOADER:
  # proposals are part of the dataset_dicts, and take a lot of RAM
  NUM_WORKERS: 2