_BASE_: "Base-YOLOv7.yaml"
MODEL:
  META_ARCHITECTURE: "YOLOMask"
  WEIGHTS: ""
  MASK_ON: True
  BACKBONE:
    NAME: "build_cspdarknetx_backbone"
  DARKNET:
    WEIGHTS: ""
    DEPTH_WISE: False
    OUT_FEATURES: ["dark2", "dark3", "dark4", "dark5"]

  YOLO:
    ANCHORS:
      # Default from COCO
      #[[142, 110], [192, 243], [459, 401], [36, 75], [76, 55], [72, 146], [12, 16], [19, 36], [40, 28]]

      # Half of COCO
      [[71, 55], [96, 121], [230, 200], [18, 38], [38, 28], [36, 73], [6, 8], [10, 18], [20, 14]]

      # Computed for wildbees_train in tools/compute_anchors.py
      #[[745, 886], [902, 656], [659, 685], [739, 575], [513, 703], [639, 475], [391, 349], [286, 328], [347, 254]]
    ANCHOR_MASK: [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
    CLASSES: 1
    IN_FEATURES: ["dark2", "dark3", "dark4", "dark5"] # p3, p4, p5 from FPN
    WIDTH_MUL: 0.50
    DEPTH_MUL: 0.33

    CONF_THRESHOLD: 0.001
    NMS_THRESHOLD: 0.65
    IGNORE_THRESHOLD: 0.7
    VARIANT: "yolov7"
    LOSS_TYPE: "v7"
    LOSS:
      LAMBDA_IOU: 1.1
    NECK:
      TYPE: "fpn"
      WITH_SPP: true

INPUT:
  MASK_FORMAT: "bitmask"
  MIN_SIZE_TRAIN: (416, 512, 608)
  MAX_SIZE_TRAIN: 608 # force max size train to 800?
  MIN_SIZE_TEST: 416
  MAX_SIZE_TEST: 608
  # open all augmentations
  RANDOM_FLIP: "none"
  JITTER_CROP:
    ENABLED: False
  RESIZE:
    ENABLED: False
    # SHAPE: (540, 960)
  DISTORTION:
    ENABLED: False
  MOSAIC_AND_MIXUP:
    ENABLED: False
    DEBUG_VIS: False
    ENABLE_MIXUP: False

SOLVER:
  #IMS_PER_BATCH: 3 # 1/5 bs than YOLOX
  # it can be 0.016 maybe
  BASE_LR: 0.01 #0.0009
  STEPS: (300, 600) #(60000, 80000)
  WARMUP_FACTOR: 0.00033333
  WARMUP_ITERS: 100 #1500
  MAX_ITER: 1000 #190000
  LR_SCHEDULER_NAME: "WarmupMultiStepLR" #"WarmupCosineLR"

TEST:
  EVAL_PERIOD: 200
OUTPUT_DIR: "output/wildbees_yolomask/half_default_anchors"

DATALOADER:
  # proposals are part of the dataset_dicts, and take a lot of RAM
  NUM_WORKERS: 1
